- 1 Run first Grand Ideas seminar
- 1 Goals & OKRs?
-   Write about economics: viability, sustainability, subscriptions, property/posessions, resources, asset class (debt vs equity)
- 1 Page on maximizing gifts & links to frugal living
-   Page on submitting other gift projects (with mine preloaded)
