
- 01 Page on submitting other gift projects (with mine preloaded) id:project-submission :
  - add search for Projects (currently only see PlanAction)
  blocks: ref:#transcendent-action

- 01 Page on submitting gratitude id:gratitude-submission :
  blocks: ref:#transcendent-action

- 01 write a plan for goals for fun :
  blocks: ref:#transcendent-action

- 02 Create crypto proposal :
  blocks : ref:#transcendent-action

- 03 Run second Grand Ideas seminar id:wishcrafting :
  blocks: ref:#transcendent-action

- 01 Goals & OKRs :
  blocks: ref:#transcendent-action

- 02 Write about economics :
  topics: viability, sustainability, subscriptions, property/posessions, resources, asset class (debt vs equity)
  blocks: ref:#transcendent-action

- 02 Page on maximizing gifts & links to frugal living :
  blocks: ref:#transcendent-action

- Collaboration with other platforms (eg Magnova.org, CompassionGames.org) :
  blocks : ref:#transcendent-action
  subtasks :
  - page of instructions for semantics and/or endpoints

- Content :
  blocks : ref:#transcendent-action
  subtasks :
  - written :
    - point
    - story
  - video

- 1000 kickstarter for time:
  blocks: ref:#transcendent-action

- 2000 fund a minimal lifestyle for 50 people, voluntarily id:minimal-lifestyle-1 :
  blocks: ref:#minimal-lifestyle-50

- 20000 fund a minimal lifestyle for 50 people, voluntarily id:minimal-lifestyle-50 :
  blocks: ref:#minimal%20fear

- 50000 build a sustainable, voluntary water delivery project :
  blocks: ref:#minimal%20fear

- regular transcendent action id:transcendent-action

- minimize temporal/external needs id:minimal%20fear

- x get observablehq page working with refs to other pages :
  blocks: ref:#project-submission

- x 01 simplify and focus website on main 2 propositions :
  blocks: ref:#transcendent-action
