- .5 include instructions for gratitude, hashtag
- 01 write a plan for goals for fun
- 03 Run first Grand Ideas seminar id:wishcrafting
- 01 Goals & OKRs?
- 02 Write about economics: viability, sustainability, subscriptions, property/posessions, resources, asset class (debt vs equity)
- 02 Page on maximizing gifts & links to frugal living
- 01 Page on submitting other gift projects (with mine preloaded)
